package com.example.eppy;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.time.LocalTime;

@Entity(tableName = "alarmTable")
public class AlarmItem {
    //getters, setters and declarations for AlarmItem fields
    public void setAlarmSet(boolean set) {
        alarmSet = set;
    }

    public boolean isAlarmSet() {
        return alarmSet;
    }

    private boolean alarmSet; //is alarm set or not

    public String getQuizURL() {
        return quizURL;
    }

    public void setQuizURL(String quizURL) {
        this.quizURL = quizURL;
    }

    private String quizURL; //api url based on AddAlarmForm responses

    public AlarmItem() {
    }

    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    //assign an autogenerated primary key for AlarmItem
    @NonNull
    @PrimaryKey(autoGenerate = true)
    private int uid;

    public String getAlarmName() {
        return alarmName;
    }

    public void setAlarmName(String alarmName) {
        this.alarmName = alarmName;
    }

    private String alarmName; //name of alarm

    public int getHour() {
        return hour;
    }

    public void setHour(int hour) {
        this.hour = hour;
    }

    private int hour; //hour alarm set for

    public int getMinute() {
        return minute;
    }

    public void setMinute(int minute) {
        this.minute = minute;
    }

    private int minute; //minutes into hour alarm set for
}
